### ISSUE TITLE
关于通栏高度的问题

### ISSUE THREAD

**Issue by inoryshu** [calimarkus/JDStatusBarNotification#102]
普通机型通知高度固定20，不能自定义，iPhoneX的通知高度却是整个导航栏高度！希望可以自定义通栏高度

**Comment by calimarkus** [comment]
Google Translate:
> "The normal model notification height is fixed at 20, can not be customized, iPhoneX notification height is the entire navigation bar height! I hope I can customize the height of the banner."

Checkout https://github.com/calimarkus/JDStatusBarNotification/pull/90 - this is a possible solution. You could follow this approach for now.
