### ISSUE TITLE
Notification on iPhone covers the entire NavBar

### ISSUE THREAD

**Issue by mattinasi** [calimarkus/JDStatusBarNotification#103]
Using the Notification on iPhone X causes the entire NavBar to be covered. User can no longer see the Nav buttons or the Title.

Is there a way to make the notification take up less of the NavBar height on iPhone X? So that it clears the 'notch' but does not cover the entire NavBar.

**Comment by calimarkus** [comment]
Yep once #90 goes in, this should be solved!

**Comment by mattinasi** [comment]
Awesome! I will keep an eye out of that merge and a new release. That PR is a month old, does it need some help?

**Comment by calimarkus** [comment]
I only had some small final comments. You could take over an finish it! It’s basically ready.

**Comment by calimarkus** [comment]
You can pull it and put it up as a new PR. Not sure if there’s a better way.
