### ISSUE TITLE
iOS 13 状态栏由statusBarManager控制，会出现显示层级问题

### ISSUE THREAD

**Issue by northcity** [calimarkus/JDStatusBarNotification#110]
有什么好的办法解决吗？

**Comment by northcity** [comment]
<img width="346" alt="屏幕快照 2019-09-10 下午5 05 27" src="https://user-images.githubusercontent.com/16768213/64600192-47fd4000-d3ed-11e9-828e-3785b0c9c7f7.png">

**Comment by northcity** [comment]
> <img alt="Screen Shot 2019-09-12 at 7 41 32 PM" width="1310" src="https://user-images.githubusercontent.com/807039/64834087-59814c00-d595-11e9-80b6-821ccd48b413.png">
> 
> Afaik iOS 13 renders the status bar in a separate process. Thus there's no way to put anything on top as you don't have access to the window.

Does that mean the status bar popover won't work after iOS 13? Or is there an alternative? Is it ok to hide the status bar when popover?

**Comment by yuratrotskyi** [comment]
Hi @calimarkus 
would it be fixed for iOS 13?

**Comment by calimarkus** [comment]
I don’t have plans to fix it for iOS 13 currently. If anyone puts up a PR I’m happy to take a look, but it would need to behave significantly differently (e.g. hide the status bar during presentation and defer the sizing in a different way).

**Comment by ezisazis** [comment]
@calimarkus  there is an open PR for fixing this issue. 💯

**Comment by calimarkus** [comment]
Merged!

**Comment by yorkwang** [comment]
It's not fixed on my project.

**Comment by QingyuHu** [comment]
It's not fixed on my project. +1

**Comment by calimarkus** [comment]
@yorkwang / @Auk513 what are you seeing? This should be the current behavior on iPhones without a notch at the top:

![Screen Recording](https://user-images.githubusercontent.com/807039/170281085-d5fe2cfa-66ab-4098-9be1-f348bec68527.gif)

With Notch:

![Screen Recording](https://user-images.githubusercontent.com/807039/170281835-5ded012c-5f37-43a3-b5fe-88dd07ef4f5c.gif)
