### ISSUE TITLE
why set the minimumPressDuration of long press gesture to 0

### ISSUE THREAD

**Issue by syt2** [calimarkus/JDStatusBarNotification#123]
why set the `minimumPressDuration` of long press gesture to `0` , this configuration will disable the tap gesture if a custom view which has a tap gesture was presented in notification.

https://github.com/calimarkus/JDStatusBarNotification/blob/00f4386a3dbfb56ddfc4703936b7b05076f9d42a/JDStatusBarNotification/Private/JDSBNotificationView.m#L74

**Comment by calimarkus** [comment]
It's a choice I made to enable the  tap-to-hold behavior without any delay. 
What's your use-case?

Without internal changes, you could try these options:
- You can disable the recognizer (and thus the tap-to-hold behavior) fully by creating a style that sets `style.canTapToHold` to `NO/false`.
- Present a custom view using `presentWithCustomView:...`

Maybe either option helps for your use-case?
