### ISSUE TITLE
[Feature Request] action handler for on-tap

### ISSUE THREAD

**Issue by pnome** [calimarkus/JDStatusBarNotification#129]
The default styles with title and subtitle and the left image are great.

I'd love to be able to submit an actionHandler to be triggered if the pill is tapped. In my use case, it's showing a title/subtitle of an inbox message and I'd like it to take the user to the inbox if they tap it.

I know I can do this with a custom view, but it seems tricky to get such a nice layout that handles longer titles, etc.

Would you consider adding a new option that allows for submitting an action for "on tap"? Perhaps handled by a button that covers the whole pill?
Or, perhaps one that will show an 'X' on the right. Tapping that would dismiss the banner, tapping anywhere else would execute the optional actionHandler?

I'm working at it with the Custom View, but if you'd think of implementing any of the above I'll just wait.

Thanks again!
Joe

**Comment by calimarkus** [comment]
I think you should be able to use the provided view, as it is returned from the presentation call. You can then add any gesture recognizers to that view, as needed. Just make sure to use a style with `.canTapToHold = false`. That disables the internal `longPressGestureRecognizer`. Setting `.canSwipeToDismiss = false` would also disable the internal `panGestureRecognizer`.

And lastly - if you need even more control - you could also copy the `JDSBNotificationView` into your project, rename it and use it as a custom view.

**Comment by pnome** [comment]
Brilliant. Thank you!
