### ISSUE TITLE
Archive failing - Missing return in instance method expected to return 'String'

### ISSUE THREAD

**Issue by ausshadu** [calimarkus/JDStatusBarNotification#134]
This error is causing the archives to fail due to missing return statement. This package is not a direct dependency, but a transient one. Unsure which (outdated) library is using the specific version. 

<img width="886" alt="Screen Shot 2023-11-14 at 11 24 07 AM" src="https://github.com/calimarkus/JDStatusBarNotification/assets/7588667/aab4fb80-eada-4a05-8969-1df5a1825e82">

Unable to proceed

<img width="489" alt="image" src="https://github.com/calimarkus/JDStatusBarNotification/assets/7588667/ffd4f53c-df86-4e19-a22a-6aae9ecc31de">

**Comment by calimarkus** [comment]
This is resolved in version 2.1.2.
See https://github.com/calimarkus/JDStatusBarNotification/commit/09e587275ea1fce1163f0f8595b8d6103440b438

Or if you use a newer SDK you also won't have issues. (Swift 5.9)

Can you force a specific version by adding an explicit dependency?

**Comment by ausshadu** [comment]
Hi @calimarkus 

Added an explicit dependency in the Podfile, and builds started working again. Thanks for the fix.

```rb
pod 'JDStatusBarNotification', '~> 2.1.2'
```

**Comment by calimarkus** [comment]
Great! FYI - that's the latest version. So you might not need to specify it explicitly.
