### ISSUE TITLE
Default Duration of 0.0 is causing most Present methods to instantly dismiss the notification

### ISSUE THREAD

**Issue by haarj** [calimarkus/JDStatusBarNotification#136]
I think this is a bug but the default duration value of 0.0 in most of the "present" methods is causing the notifications to instantly be dismissed making it seem like they never showed in the first place. I think instead of 0.0, the value of "duration" should be "nil", which is what you are checking for in the first place. 

This was working before. Not sure what changed...

This is happening in NotificationPresenterLegacyOverlay, which is being called from my Objc code.

**Comment by calimarkus** [comment]
Thank you! Could you try the latest commit on master?

**Comment by haarj** [comment]
@calimarkus works like a charm. Thanks!

**Comment by calimarkus** [comment]
Awesome. I published it as `2.2.1` now.
