### ISSUE TITLE
Compilation error (on Xcode 14, iOS 11, Swift 5)

### ISSUE THREAD

**Issue by dslcoding** [calimarkus/JDStatusBarNotification#137]
![image](https://github.com/calimarkus/JDStatusBarNotification/assets/26846337/c3576a99-f434-4707-9cc9-78513c18175a)

**Comment by calimarkus** [comment]
You are trying to run it on an iOS11 device using Xcode14? Is that the only errors you are seeing? I am using a bunch of iOS 13 only APIs at this point. So I'm not sure, if this back deploys to older iOS versions anymore.
