### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by LittIe-ma** [calimarkus/JDStatusBarNotification#138]
Do you have any plans to add a Privacy Manifest to this library?
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

Is this library not required to be supported?

Thank you very much!

**Comment by calimarkus** [comment]
It's purely a UI library. No data collected. No user permissions required.

**Comment by LittIe-ma** [comment]
I understand.
Thank you for your response.
