### ISSUE TITLE
Tap to dismiss on SwiftUI

### ISSUE THREAD

**Issue by metallica1375** [calimarkus/JDStatusBarNotification#141]
hey, thanks for your awesome library, how can I dismiss the toast or notification in swiftUI form?

**Comment by calimarkus** [comment]
Dismissing a notification

```
NotificationPresenter.shared.dismiss()

// with completion
NotificationPresenter.shared.dismiss(after: 0.5) { presenter in
   // ...
}
```

**Comment by metallica1375** [comment]
Thanks for the hint, but when I call it, it won't work, e.g. in onTagGesture{} in my SwiftUI view component. although I added the onTapDismiss functionality in my fork using UITapGestureRecognizer, but I wanted to check if it can be done directly or not.

**Comment by calimarkus** [comment]
Ah you want to handle custom user interaction? See this sample code:

https://github.com/calimarkus/JDStatusBarNotification/blob/main/ExampleProject/ExamplesScreen.swift#L268-L274

**Comment by metallica1375** [comment]
No no, I just want to simply dismiss the notification when the user taps anywhere on it

**Comment by calimarkus** [comment]
Yep, for that you need the above. Then you can use swift gesture handling as usual.

By default a user can only swipe to dismiss.
