### ISSUE TITLE
swiftUI view is not vertical centered on notch devices

### ISSUE THREAD

**Issue by noah-z** [calimarkus/JDStatusBarNotification#142]
Tested on 12, 13, 14, 15 Pro simulator, and 12 Pro max real device
SwiftUI view is not vertical centered on notch devices and is centered on dynamic island devices.

![snapshot](https://github.com/user-attachments/assets/917e7ca3-bd41-44ef-96ad-754421295f68)

**Comment by calimarkus** [comment]
Thanks for the feedback, I'll need to debug this. Or maybe you want to take a look at it yourself and open a PR?

**Comment by calimarkus** [comment]
Resolved!


| Example 1 | Example 2 |
|--------|--------|
| <img width="394" alt="nonotch1" src="https://github.com/user-attachments/assets/265fe8b2-42a3-4e2d-8ff8-f462fb265177"> | <img width="399" alt="nonotch2" src="https://github.com/user-attachments/assets/1b6c1686-ef3c-47cc-be5c-0768b9dd1264"> |
| <img width="419" alt="notch1" src="https://github.com/user-attachments/assets/0c7be613-476c-43a3-b9c3-32f835bfdbfd"> | <img width="388" alt="notch2" src="https://github.com/user-attachments/assets/54297736-37a0-4210-8ca0-58f227d5742a"> |
| <img width="422" alt="island1" src="https://github.com/user-attachments/assets/1935c8cc-6b79-4c13-9506-ddfa5b453313"> | <img width="425" alt="island2" src="https://github.com/user-attachments/assets/c4a03a1b-cf8a-469e-9336-ba8fff6c80ac"> |
