### ISSUE TITLE
Use LocalizedStringKey for title/subtitle parameters

### ISSUE THREAD

**Issue by CleverLemming1337** [calimarkus/JDStatusBarNotification#145]
Using them for title and subtitle would support localization for notification content with a string catalog.

**Comment by calimarkus** [comment]
Can you be more explicit here? Can't you pass already localized strings to the framework?

**Comment by CleverLemming1337** [comment]
I mean that changing the type of title and subtitle from `String` to `LocalizedStringKey` would list all used strings in a string catalog to adapt them to the different languages. 
As far as I know it's not possible to do that with Strings.

**Comment by calimarkus** [comment]
Sadly that won't work, as the view itself is implemented using UILabels. So you have to use `NSLocalizedString("string-key", comment: "")` to pass localized strings to the `present()` functions. Or use the newer `presentSwiftView(styleName:viewBuilder:completion:)` to present a custom swift view.
