### ISSUE TITLE
SwiftUI View text gets trimmed instead of e.g. using two lines

### ISSUE THREAD

**Issue by metallica1375** [calimarkus/JDStatusBarNotification#146]
Hi, when I use this in SwiftUI when the text is too long it wont become taller to show the text in two line for example, it trims the end of it like (...) this

**Comment by calimarkus** [comment]
Are you referring to using `NotificationPresenter.presentSwiftView(styleName:viewBuilder:completion:)`? If so - you are responsible for the text layout in your Swift view.

Otherwise, the default behavior is to grow the bubble until 100%, then shrink the text to fit.

**Comment by metallica1375** [comment]
Yes I'm referring to using ```NotificationPresenter.presentSwiftView(styleName:viewBuilder:completion:)``` . When I use this the height of any kind of swiftUI view inside that is fixed. If I want to change the height I should change the ```style.backgroundStyle.pillStyle.height``` inside of ```NotificationPresenter.shared.updateDefaultStyle``` lambda function.

**Comment by calimarkus** [comment]
The height is currently fixed and won't grow automatically. You can however control it through the style, as you mentioned.

`style.backgroundStyle.pillStyle.height = xx`.

You could also try using a `minimumScaleFactor` to shrink the text as needed to fit. `Text()` does allow multilines by default.
