### ISSUE TITLE
App Rejected

### ISSUE THREAD

**Issue by goelv** [calimarkus/JDStatusBarNotification#15]
Hi,

I would like to inform you that my app got rejected for violating 10.1/10.3.

10.1: Apps must comply with all terms and conditions explained in the Apple iPhone Human Interface Guidelines and the Apple iPad Human Interface Guidelines
10.3: Apps that do not use system provided items, such as buttons and icons, correctly and as described in the Apple iPhone Human Interface Guidelines and the Apple iPad Human Interface Guidelines may be rejected

10.1/10.3

We also found that your app does not comply with the Apple iOS Human Interface Guidelines, as required by theApp Store Review Guidelines.

Specifically, we found that your app displays an overlay over the status bar. It would be appropriate to revise your app so that it does not display a status bar overlay when loading content.

It may be helpful to review the iOS Human Interface Guidelines to help ensure your app is in compliance with these terms and conditions. 

Learn more about system-provided items in the iOS Human Interface Guidelines, sections: "System-Provided Buttons and Icons" and "iOS UI Element Usage Guidelines."

Has anyone else seen this issue from Apple? I dont think I have any choice, but to remove this from my app.

Thanks,
Varun

**Comment by alimoeeny** [comment]
@goelv can you please explain how you used this library that ended up in rejection? Or can you please  post a screenshot. Basically I want to know what counts as violation of the HIG. Thanks.

**Comment by goelv** [comment]
Hey @alimoeeny I used this library to overlay contextual messages on top of the status bar depending on user actions. However, even though multiple apps do it today, at the time, the reviewer didn't appreciate it and rejected it. As soon I fixed that issue, and resubmitted it, app got approved.

**Comment by alimoeeny** [comment]
Thanks @goelv
