### ISSUE TITLE
Undefined symbols for architecture armv7s

### ISSUE THREAD

**Issue by bolee** [calimarkus/JDStatusBarNotification#22]
My Xcode 5.1, my workspace using Cocoapods, but build for my iPhone 5s,xcode' error is:
Undefined symbols for architecture armv7s:
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

It not support Xcode5.1 or my project setting is wrong?

**Comment by aetherwu** [comment]
I got this:

Undefined symbols for architecture arm64:
  "_CATransform3DMakeTranslation", referenced from:
      -[JDStatusBarNotification animateInWithBounceAnimation] in JDStatusBarNotification.o
  "_OBJC_CLASS_$_CAKeyframeAnimation", referenced from:
      objc-class-ref in JDStatusBarNotification.o
  "_OBJC_CLASS_$_CAMediaTimingFunction", referenced from:
      objc-class-ref in JDStatusBarNotification.o
  "_kCAFillModeForwards", referenced from:
      -[JDStatusBarNotification animateInWithBounceAnimation] in JDStatusBarNotification.o
  "_kCAMediaTimingFunctionLinear", referenced from:
      -[JDStatusBarNotification animateInWithBounceAnimation] in JDStatusBarNotification.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by jaydee3** [comment]
Sounds like you didn't link CoreAnimation... can't check the example project right now.
