### ISSUE TITLE
This kind of statusbar will be rejected by apple

### ISSUE THREAD

**Issue by dskyu** [calimarkus/JDStatusBarNotification#30]
This is apple's reason for rejection.

----- 10.1 -----

Moreover, we found that your app does not comply with the Apple iOS Human Interface Guidelines, as required by the App Store Review Guidelines.

Specifically, we found that the app inappropriately covers the native iOS status bar.

It may be helpful to review the iOS Human Interface Guidelines to help ensure your app is in compliance with these terms and conditions. 

----- 10.3 -----

In addition, we found your app uses system-provided items in a non-standard manner, which is not in compliance with the App Store Review Guidelines.

Specifically, we found that the app attempts to replace or cover information on the native iOS status bar.

This kind of style covers the native iOS status bar, I find a better way to modify. 

![Screenshot](http://lianaibiji-admin.u.qiniudn.com/QQ20141029-1.png)

**Comment by alimoeeny** [comment]
@dskyu can you please explain how you used this library that ended up in rejection? Or can you please  post a screenshot. Basically I want to know what counts as violation of the HIG. Thanks.

**Comment by yorkwang** [comment]
My app was rejected by the same reason, apple doesn't allow app cover the status bar.
