### ISSUE TITLE
Locking device with notification visible causes overlap upon unlock

### ISSUE THREAD

**Issue by dhalman** [calimarkus/JDStatusBarNotification#48]
Tried dismissing the notification before the app resigns active and re-showing when app becomes active... Behavior is a clear status bar message the covers the visible status bar momentarily, then replaces with a solid white notification that hides the status bar.

Just updated to version 1.5.1

**Comment by jaydee3** [comment]
Do you have screenshots or a video? Maybe you just need to user other state notifications. (UIApplicationDidEnterBackgroundNotification / UIApplicationWillEnterForegroundNotification)?

**Comment by dhalman** [comment]
![screen shot 2015-06-12 at 12 20 28 pm](https://cloud.githubusercontent.com/assets/1349742/8138197/7bdc3410-10fd-11e5-995f-1e2ed38b655e.png)

This is taken during a breakpoint on the first line of applicationWillEnterForeground

**Comment by dhalman** [comment]
It appears that the dismiss call in willResignActive and didEnterBackground both fail to animate until after the app becomes active again, effectively dismissing and then re-showing the notification after the app is relaunched. 

The notification would not need to be dismissed if it did not show the status bar underneath it after locking and unlocking the screen with the app in the foreground.

**Comment by lilin87788** [comment]
i have same issue with this

**Comment by Kieranator** [comment]
I am also experiencing this issue.

**Comment by dhalman** [comment]
Any update?

**Comment by calimarkus** [comment]
I just released a major update (Version 2.0). If this still happens / reproduces, please reopen this issue.
