### ISSUE TITLE
Random Black screen on iPad

### ISSUE THREAD

**Issue by MOLO17** [calimarkus/JDStatusBarNotification#54]
There might be a problem while presenting the status bar with the code pasted below, it appears only on iPad (i've tested it with an iPad Air iOS 8.4.1), tested also with both iPhone 5-5s-6-6plus and it doesn't appear. 

the way i set it up:
[JDStatusBarNotification setDefaultStyle:^JDStatusBarStyle *(JDStatusBarStyle *style) {
        style.barColor = companyColor();
        style.textColor = [UIColor whiteColor];
        style.animationType = JDStatusBarAnimationTypeMove;
        style.progressBarColor = style.textColor;
        style.progressBarHeight = 2.0;
        style.font = [LCUtils fontWithSize:14];
        style.progressBarPosition = JDStatusBarProgressBarPositionTop;
        return style;
    }];

the way i present it
[JDStatusBarNotification showProgress:[engine.overallReplicationProgress unsignedIntegerValue]];

the screen flashes and it show up like in the screenshot
![img_0240](https://cloud.githubusercontent.com/assets/3962640/10263421/f4aedb82-69ee-11e5-8b8a-3c26e72ac761.PNG)

thank you!

**Comment by calimarkus** [comment]
I just released a major update (Version 2.0). If this still happens / reproduces, please reopen this issue.
