### ISSUE TITLE
 In plus iPhone6s 9.3 above with the progress bar, has been flashing,  how to solve it，  thank you

### ISSUE THREAD

**Issue by shuolol** [calimarkus/JDStatusBarNotification#64]
In plus iPhone6s 9.3 above with the progress bar, has been flashing,  how to solve it 

thank you

**Comment by shuolol** [comment]
I found a way to solve this problem. I put him in a thread to execute, put in the main thread is good

**Comment by calimarkus** [comment]
I just released a major update (Version 2.0). If this still happens / reproduces, please reopen this issue.
