### ISSUE TITLE
add a function to temporarily hide topBar

### ISSUE THREAD

**Issue by jeromeDms** [calimarkus/JDStatusBarNotification#73]
Hi
Thanks for your great work.
In my app, I use your JDStatusBarNotification with progress bar while uploading large files to my server. This works fine.
While the upload is in progress, the user may click a photo on another view, this photo will be displayed full screen, and the app status bar is automatically hidden while the photo is full screen, I'd like to be able to also hide the JDStatusBarNotification while the app status is hidden, since bidding the app status bat does not hide the JDStatusBarNotification.
Any way to achieve this ?
Thanks

**Comment by calimarkus** [comment]
I just released a major update (Version 2.0). If this still happens / reproduces, please reopen this issue.
There's APIs to dismiss/present without an animation. Would that help?
