### ISSUE TITLE
Doesn't show the notification bar at times?

### ISSUE THREAD

**Issue by arpwal** [calimarkus/JDStatusBarNotification#77]
Hey @calimarkus thanks for the library. Works very well. However, at times the notification bar doesn't show up when called. I'm using the method -- 

`JDStatusBarNotification.show(withStatus: message, dismissAfter: 2.0)`

If you are also seeing this issue, then great, else I can post the logs. 

Thanks.

**Comment by ricardopereira** [comment]
@arpwal This is happening to me as well! Did you have any clue of what could be the issue? Or did you apply any workaround?

**Comment by ricardopereira** [comment]
@arpwal It only fails the first time you show a status message, right?

**Comment by calimarkus** [comment]
I just released a major update (Version 2.0). If this still happens / reproduces, please reopen this issue.

I realized there was an issue when presenting during a previous dismiss animation. This is no longer an issue. Maybe it was this?
