### ISSUE TITLE
iPhone X?

### ISSUE THREAD

**Issue by hansemannn** [calimarkus/JDStatusBarNotification#80]
So here we are, cracking our heads about the iPhone X. The bezier-shape of it will make status-bar notifications impossible from now on:

![simulator screen shot - iphone x - 2017-09-13 at 20 33 36](https://user-images.githubusercontent.com/10667698/30394326-0faef6b0-98c3-11e7-8e6a-9c64b7fb098e.png)

Is there a plan for resolving this? Or an alternative for those target-devices?

**Comment by calimarkus** [comment]
We can respect the safe inset and make it larger for the X. Happy to accept a PR!

**Comment by chquanquan** [comment]
I've fixed the iPhone X problem, can you accept my PR, thanks.

**Comment by calimarkus** [comment]
I put up a fix similar to #83 from @chquanquan - this shows the bar on top of the whole navbar.
This will be super akward for non navbar interfaces though.. but still better than the current situation. So that's that for now.

**Comment by genadyo** [comment]
@calimarkus Can you push new Cocoapods release?

**Comment by calimarkus** [comment]
Done!
