### ISSUE TITLE
iOS 11 issue with rotation

### ISSUE THREAD

**Issue by smolskyaleksey** [calimarkus/JDStatusBarNotification#87]
Wrong frame and orientation of JDStatusBarNotification when present viewcontroller in another orientation for iPhone 8. For iPhone X JDStatusBarNotification is hide.
![simulator screen shot - iphone 8 - 2017-10-10 at 17 14 52](https://user-images.githubusercontent.com/6605765/31391210-8eba5abe-adde-11e7-90c8-955461693b2c.png)
![simulator screen shot - iphone x - 2017-10-10 at 17 16 05](https://user-images.githubusercontent.com/6605765/31391327-db753ff4-adde-11e7-915a-c9f20f64660c.png)
![simulator screen shot - iphone x - 2017-10-10 at 17 16 23](https://user-images.githubusercontent.com/6605765/31391328-db95537a-adde-11e7-9c91-2852b6e16c27.png)
![simulator screen shot - iphone x - 2017-10-10 at 17 16 27](https://user-images.githubusercontent.com/6605765/31391330-dbbedb82-adde-11e7-89b9-9f20aa1d3723.png)

Steps:
1.Open example project 
2.rotate to landscape 
3.press 'Button'
[TestStatus.zip](https://github.com/calimarkus/JDStatusBarNotification/files/1372199/TestStatus.zip)

**Comment by calimarkus** [comment]
Is that fixed when you go one version back?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by smolskyaleksey** [comment]
No. it is also exist in 1.5.5

**Comment by calimarkus** [comment]
I just released a major update (Version 2.0). If this still happens / reproduces, please reopen this issue.
