### ISSUE TITLE
We noticed your app does not satisfy the requirements outlined in the Apple iOS Human Interface Guidelines. Specifically, your app places an overlay on top of the status bar.

### ISSUE THREAD

**Issue by hongdong** [calimarkus/JDStatusBarNotification#91]
We noticed your app does not satisfy the requirements outlined in the Apple iOS Human Interface Guidelines. Specifically, your app places an overlay on top of the status bar.
<img width="375" alt="attachment-5737736190423355536screenshot_1212_084308" src="https://user-images.githubusercontent.com/5499518/33980785-4d31165c-e0e5-11e7-945c-5fbb729b8015.png">

**Comment by calimarkus** [comment]
Yep, I state this in the main readme. I'll add your notice there too. Thanks!

> **Beware**
@goelv / @dskyu / @graceydb informed me (see #15, #30, #49), that his app got rejected because of a status bar overlay (for violating 10.1/10.3). So don't overuse it. Although I haven't heard of any other cases.

**Comment by calimarkus** [comment]
Readme updated, see commit: b83f281f3509a99c5861793422fa5f30e4a50dac
