### ISSUE TITLE
 [self updateTopBarFrameWithStatusBarFrame:[[UIApplication sharedApplication] statusBarFrame]];

### ISSUE THREAD

**Issue by microponts** [calimarkus/JDStatusBarNotification#92]
[self updateTopBarFrameWithStatusBarFrame:[[UIApplication sharedApplication] statusBarFrame]];

I updated the latest code and found that the status bar was not available. can't get the FrameSize!

**Comment by calimarkus** [comment]
What's your issue? Can you describe this in more detail?
