### ISSUE TITLE
Carthage failed to build

### ISSUE THREAD

**Issue by thang2410199** [calimarkus/JDStatusBarNotification#93]
Look like the files `JDStatusBarLayoutMarginHelper.m` and `JDStatusBarLayoutMarginHelper.h` are missing from the project (but still included in the repo) when carthage check out.

When I manually add those file to the project, it can build without error.

**Comment by calimarkus** [comment]
Carthage support was introduced in #86 by @VFUC - if you or him could go ahead and fix it, I'd merge it!
